/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.home.mierzwiak.franciszek.formularzdaneosobowe;

import java.text.SimpleDateFormat;

/**
 *
 * @author frane
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLLogin = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jLEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLHeight = new javax.swing.JLabel();
        jTFHeight = new javax.swing.JTextField();
        jLWeight = new javax.swing.JLabel();
        jTFWeight = new javax.swing.JTextField();
        jLBirthdate = new javax.swing.JLabel();
        jCBirthdate = new com.toedter.calendar.JCalendar();
        jBSubmit = new javax.swing.JButton();
        jLError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLLogin.setText("Login");
        jLLogin.setToolTipText("2-20 znakow");

        jTFLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFLoginActionPerformed(evt);
            }
        });

        jLEmail.setText("Email");
        jLEmail.setToolTipText("musi zawierac 1-@ i 1-. ; . po @ ; co najmniej 1 znak przed @, pomiedzy @ i . oraz po .; tylko litery");

        jTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailActionPerformed(evt);
            }
        });

        jLHeight.setText("Wzrost");
        jLHeight.setToolTipText("tylko cyfry");

        jTFHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFHeightActionPerformed(evt);
            }
        });

        jLWeight.setText("Waga");
        jLWeight.setToolTipText("tylko cyfry");

        jTFWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFWeightActionPerformed(evt);
            }
        });

        jLBirthdate.setText("Data Urodzenia");

        jBSubmit.setText("WYSLIJ");
        jBSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFLogin))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jCBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFLoginActionPerformed

    private void jTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailActionPerformed

    private void jTFHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFHeightActionPerformed

    private void jTFWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFWeightActionPerformed

    private void jBSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubmitActionPerformed
        //sprawdzenie czy login nie posiada spacji
        boolean LoginError = true;
        String login = jTFLogin.getText();
        if(login.length() >= 2 && login.length() <= 20){
            LoginError = false;
        }
        //sprawdzenie poprawnosci emaila
        boolean EmailError = true;
        String email = jTFEmail.getText();
        if(email.contains("@") && email.indexOf("@") > 0 && email.indexOf("@")+1 < email.length()){ //czy email zawiera @ i czy @ nie jest na początku albo koncu
            String ema1[] = email.split("@");
            String emaFinal = ema1[0] + ema1[1] + "a";
            if(emaFinal.length() == email.length()){ //czy email nie zawiera kilku @
                if(ema1[1].contains(".") && ema1[1].indexOf(".") > 0 && ema1[1].indexOf(".")+1 < ema1[1].length()){ //czy email zawiera . i czy . nie jest na początku albo koncu
                    String ema2[] = ema1[1].split("\\.");
                    emaFinal = ema2[0] + ema2[1] + "a";
                    if(emaFinal.length() == ema1[1].length()){ //czy email nie zawiera kilku .
                        EmailError = false;
                        for(int i=0; i<email.length(); i++){
                            char ch = email.charAt(i);
                            if(ch == '@'); //pominiecie @
                            else if(ch == '.'); //pominiecie .
                            else if(!((ch >= 'A' && ch<= 'Z') || (ch <= 'z' && ch>= 'a'))){ //sprawdzanie czy są same litery
                                EmailError = true;
                            }
                        }
                    }
                }
            } 
        }
        
        boolean HeightError = false;
        String height = jTFHeight.getText();
        if(height.length() <= 0) HeightError = true; //czy nie jest puste
        for(int i=0; i<height.length(); i++){
            char ch = height.charAt(i);
            if(!((ch >= '0' && ch <= '9'))){ //sprawdzanie czy są same litery
                HeightError = true;
            }
        }
        boolean WeightError = false;
        String weight = jTFWeight.getText();
        if(weight.length() <= 0) WeightError = true; //czy nie jest puste
        for(int i=0; i<weight.length(); i++){
            char ch = weight.charAt(i);
            if(!((ch >= '0' && ch <= '9'))){ //sprawdzanie czy są same litery
                WeightError = true;
            }
        }
        
        if(LoginError == false && EmailError == false && HeightError == false && WeightError == false){
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-y");
            SaveToFile stf = new SaveToFile();
            String text = jTFLogin.getText().trim()+";"+jTFEmail.getText().trim()+
                    ";"+jTFHeight.getText().trim()+";"+jTFWeight.getText().trim()+
                    ";"+sdf.format(jCBirthdate.getDate()).trim();
            stf.saveToFile(text);
            jLError.setText("");
            
        }else{
            jLError.setText("<html>");
            if(LoginError == true) jLError.setText(jLError.getText()+"zly login<br>");
            if(EmailError == true) jLError.setText(jLError.getText()+"zly email<br>");
            if(HeightError == true) jLError.setText(jLError.getText()+"zly wzrost<br>");
            if(WeightError == true) jLError.setText(jLError.getText()+"zla waga<br>");
            jLError.setText(jLError.getText()+"</html>");
        }
    }//GEN-LAST:event_jBSubmitActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSubmit;
    private com.toedter.calendar.JCalendar jCBirthdate;
    private javax.swing.JLabel jLBirthdate;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLError;
    private javax.swing.JLabel jLHeight;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLWeight;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFHeight;
    private javax.swing.JTextField jTFLogin;
    private javax.swing.JTextField jTFWeight;
    // End of variables declaration//GEN-END:variables
}
